site_name: Hackspace Manchester Documentation
site_url: https://docs.hacman.org.uk
repo_url: https://github.com/HACManchester/documentation/

theme:
  name: material
  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - navigation.instant # better loading of internal links
    - navigation.tabs # top-level sections appear in menu header
    - navigation.path # show path at top of page
    - navigation.indexes # allows overview page for each section
    - toc.follow # side-bar keeps up with current location
    - navigation.top # 'back to top' button
    - navigation.footer # 'Next' and 'previous' page links in footer

plugins:
  - search # Allows searching through documentation
  - macros # Used for global link list defined below
  - emailprotect # protects email addresses from bots
  - awesome-nav: # easy page navigation design
      filename: navigation_structure.yml
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list

extra_javascript:
  - assets/js/hljs/config.js

    # Sortable tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/js/sorttable/config.js

extra_css:
  - extra.css

extra:
  # Define links throughout the document here.
  # If the link changes, we only have to change 
  # it here to change it everywhere else.
  links:
    risk_assessments: https://drive.google.com/drive/folders/1gNdDUavZLfXFX8dfru6wcbcLSanm1Sv-?usp=sharing
    consumables_list: https://docs.google.com/spreadsheets/d/1AOO55t0vs3c4PiPQu42w1USbfekBcNd9CSx9lppWmmY/edit?usp=sharing
    broken_equipment_form: https://forms.gle/UT92ABZ2mFttCrY6A
    accident_form: https://forms.gle/UT92ABZ2mFttCrY6A
    formal_incident_form: https://forms.gle/HC2xJrz1XcXx4W1w7
    space_calendar: https://www.hacman.org.uk/calendar/
    telegram: https://t.me/hacmanchester
    forum: https://list.hacman.org.uk/
    events_box_office: https://www.tixtree.com/o/manchester-hackspace-d5c0001fd603
    members_portal: https://members.hacman.org.uk
    website: https://www.hacman.org.uk/
    instagram: https://www.instagram.com/hacmanchester
    visit_us: https://www.hacman.org.uk/visit-us/